version: '3'

services:
  llm-server-1:
    build: .
    container_name: llm-sever
    ports:
      - "8888:8000"
    networks:
      - nginx-bridge
    env_file: "${DEPLOY_PROFILE}"

  llm-server-2:
    build: .
    container_name: llm-server2
    ports:
      - "8889:8000"
    networks:
      - nginx-bridge
    env_file: "${DEPLOY_PROFILE}"

networks:
  nginx-bridge:
    external: true
